name: Autograding Tests
'on':
  repository_dispatch: []
  schedule:
  - cron: '16 11 * * *'
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: teste
      id: teste
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: teste
        setup-command: ''
        command: maven test
        timeout: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TESTE_RESULTS: "${{steps.teste.outputs.result}}"
      with:
        runners: teste
